// Redux/src/views/Login.jsx
import React from 'react'
import { Form, Input, Checkbox, Button, message } from 'antd'
import { myapi,request}  from '@/utils/request'
import { connect } from 'react-redux';

import querystring from 'querystring'

import cryptoJS,{SHA256,enc} from 'crypto-js'  // 加密

const layout = {
    labelCol: {
        span: 6,
    },
    wrapperCol: {
        span: 16,
    },
};


const tailLayout = {
    wrapperCol: {
        offset: 6,
        span: 16,
    },
};

const mapStateToProps = function (state) {
    return {}
}
const mapDispatchToProps = function (dispatch) {
    return {
        login(userInfo) {
            dispatch({ type: 'login', userInfo })
        }
    }
}

@connect(mapStateToProps,mapDispatchToProps)
class Login extends React.Component {
    state = {
        rules: {
            username: [
                {
                    required: true,
                    message: '请输入用户名',
                },
            ],
            password: [
                {
                    required: true,
                    message: '请输入密码',
                },
            ]
        }

    }
    onFinish = async (values) => {
        // console.log(values, 666);
        const { login,location,history } = this.props;
        let { username, password, md1 } = values;

        password=SHA256(password);
        password = enc.Hex.stringify(password)
        console.log('3',password)

    //    发请求
        const { data } = await myapi.get('user/login', {
            username,
            password, md1
        });

        if (data.code === 200) {
            login(data.data);
            // this.props.history.push('/mine')
            const {redirectTo='/mine'} = querystring.parse(location.search.slice(1))
            history.push(redirectTo)
        }else{
            message.error('用户名或密码错误')
        }
    };

    render() {
        const { rules } = this.state;
        return (
            <div>
                <Form style={{ padding: 60 }}
                    {...layout}
                    name="basic"
                    initialValues={{
                        remember: true,
                    }}
                    onFinish={this.onFinish}

                >
                    <Form.Item
                        label="用户名"
                        name="username"
                        rules={rules.username}
                    >
                        <Input />
                    </Form.Item>

                    <Form.Item
                        label="密码"
                        name="password"
                        rules={rules.password}
                    >
                        <Input.Password />
                    </Form.Item>

                    <Form.Item {...tailLayout} name="remember" valuePropName="checked">
                        <Checkbox>7天免登录</Checkbox>
                    </Form.Item>

                    <Form.Item {...tailLayout}>
                        <Button type="primary" htmlType="submit">
                            登录
                </Button>
                    </Form.Item>
                </Form>
            </div>
        )

    }
}



export default Login;

// Vuex/uicy/src/views/Login.vue
<template>
    <div>
        <h1>用户登录</h1>
        <el-form :model="ruleForm" status-icon :rules="rules" ref="loginForm" label-width="100px"
            @keyup.native.enter="submitForm" >
            <el-form-item label="用户名" prop="username" :error="errMsg">
                <el-input v-model="ruleForm.username"  ></el-input>
            </el-form-item>
            <el-form-item label="密码" prop="password" :error="errMsg">
                <el-input type="password" v-model="ruleForm.password" autocomplete="off"
                @keyup.enter="submitForm"></el-input>
            </el-form-item>
            <el-form-item prop="mdl">
                <el-checkbox v-model="ruleForm.mdl">7天免登陆</el-checkbox>
            </el-form-item>
            <el-form-item>
                <el-button type="primary" @click="submitForm">登录</el-button>
            </el-form-item>
        </el-form>
    </div>
</template>
<script>
    const crypto = require('crypto')
    export default {
        name: 'Login',
        data() {
            return {
                errMsg: '',
                ruleForm: {
                    username: "",
                    password: "",
                    mdl: true,
                },
                rules: {
                    username: [{
                            required: true,
                            message: "请输入用户名",
                            trigger: "blur"
                        },
                        {
                            min: 3,
                            max: 20,
                            message: "用户名长度必须在3到20",
                            trigger: "blur",
                        },
                    ],
                    password: [{
                            required: true,
                            message: "请输入密码",
                            trigger: "blur"
                        },
                        {
                            min: 6,
                            max: 12,
                            message: "密码长度必须在6到12",
                            trigger: "blur",
                        },
                    ],
                },
            };
        },
        methods: {
            submitForm() {
                this.$refs.loginForm.validate(async (valid) => {
                    if (valid) {
                        const {
                            username,
                            password
                        } = this.ruleForm;
                        // 加密
                        const hash = crypto.createHash("sha256");
                        hash.update(password);
                        const newPassword = hash.digest("hex");

                        // 发起ajax请求注册
                        const {
                            data
                        } = await this.$ajax.get("/user/login", {
                            params: {
                                username,
                                password: newPassword
                            },
                        });
                        if (data.code == 200) {
                            // 跳转
                            // this.$router.replace("/home");
                        let {redirectTo='/mine'}=this.$route.query;  // 给个默认值
                        this.$router.replace(redirectTo)

                            // 把用户信息保存到vuex
                            this.$store.commit( 'login', data.data);
                        } else {
                            // this.$message.error("用户名或密码错误");
                            this.errMsg = '用户名或密码错误';
                        } 

                        // this.$store.dispatch('login',{
                        //      username,
                        //         password: newPassword
                        // })
                    } else {
                        console.log("error submit!!");
                        return false;
                    }
                });
            },
        },
        // 获取数据
        created() { 
            console.log('store=', this.$store);
            console.log('state=', this.$store.state.user.username);
            console.log('getters=', this.$store.getters.totalPrice);
        }
    }
</script>
