// React/src/components/TodoList/TodoItem.js
import React from 'react'
import classNames from 'classnames'

import MyContext from './context'
import TodoButton from './TodoButton'

function TodoItem({ item, idx }) {
    return (
        <tr className={classNames({'table-success':item.complete})}>
            <th>{idx + 1}</th>
            <td>{item.todo}</td>
            <td>{item.complete ? '是' : '否'}</td>
            <td>
                {/* 接收数据 */}
                <MyContext.Consumer>
                    {
                        (value) => {
                            console.log(value);
                            return (
                                //    {/* 不会生成标签 */}
                                <React.Fragment>
                                     {/* <button className="btn btn-outline-primary btn-sm" onClick={value.complete.bind(null,item.id)}>完成</button>
                                   <button className="btn btn-outline-danger btn-sm" onClick={value.remove.bind(null,item.id)}>删除</button>  */}
                                    <TodoButton className="btn-outline-primary" onClick={value.complete.bind(null,item.id)}>完成</TodoButton>
                                   <TodoButton className="btn-outline-danger" onClick={value.remove.bind(null,item.id)}>删除</TodoButton>
                                </React.Fragment>
                            )
                        }
                    }

                </MyContext.Consumer>
            </td>
        </tr>
    )
}

export default TodoItem

// vue-cli/antony/src/components/Todolist/TodoItem.vue
<template>

    <tr :id="item.id" :class="{'table-success':item.complete}">
        <th scope="row">{{idx+1}}</th>
        <td>{{item.event}}</td>
        <td>{{item.complete ? '是':'否'}}</td>
        <td>
            <button class="btn btn-outline-primary btn-sm" @click="complete(item.id)">完成</button>
            <button class="btn btn-outline-danger btn-sm" @click="remove(item.id)">删除</button>
        </td>
    </tr>
</template>

<script>
import Bus from "./Bus";

    export default {
        name: "TodoItem",
        props: ["item", "idx"],
   
        //   方法
        methods: {
            complete(id) {
                // 触发事件并传递数据
                Bus.$emit("complete", id);
                // this.$root.$emit('complete', id);
            },
            remove(id) { 
                Bus.$emit("remove", id);
                // this.$root.$emit('remove', id);

            }


        },


    };
</script>
