// Redux/src/App.jsx
import React from 'react'
import { Route, Link, Redirect, Switch, NavLink, withRouter } from 'react-router-dom'
import Home from './views/Home'
import Login from './views/Login'
import Reg from './views/Reg'
import Discover from './views/Discover'
import Mine from './views/Mine'
import IQ from './views/IQ'

import { Menu, Layout, Row, Col, Button, Avatar } from 'antd';

import {
    HomeOutlined,
    LoginOutlined,
    UserOutlined,
    EyeOutlined,

} from '@ant-design/icons';


import { baseURL } from '@/utils/request'
// import userAction from './store/actions/user'
import 'antd/dist/antd.css'
import './App.scss';
import { connect } from 'react-redux'


function App(props) {
    // console.log(props);
    const currentPath = props.location.pathname
    const nav = [{
        path: '/home',
        text: '首页',
        name: 'home',
        icon:
            <HomeOutlined />

    }, {
        path: '/discover',
        text: '发现',
        name: 'discover',
        icon:
            <EyeOutlined />

    }, {
        path: '/mine',
        text: '我的',
        name: 'mine',
        icon: <UserOutlined />
    }
        // {
        //     path: '/login',
        //     text: '登录',
        //     name: 'login',
        //     icon:
        //         <LoginOutlined />

        // }, {
        //     path: '/reg',
        //     text: '注册',
        //     name: 'reg',
        //     icon:
        //         <UserOutlined />
        // }
    ];

    const changeMenu = function ({ key }) {
        // console.log(e);
        // 跳转
        props.history.push(key);

    }

    const goto = function (path, e) {
        console.log(path, 666, e);
        props.history.push(path)
    }

    return <Layout>
        <Layout.Header style={{ padding: 0 }}>
            {/* {
    nav.map(item=><NavLink key={item.name} to={item.path} // activeStyle={{color:'#f00',fontWeight:'bold'}}
        activeClassName='active'>{item.text}</NavLink>)
    } */}
            <Row gutter={10}>
                <Col span={16}>
                    <Menu mode="horizontal" theme="dark" onClick={changeMenu} defaultSelectedKeys={[currentPath]}>
                        {
                            nav.map(item => <Menu.Item key={item.path} icon={item.icon}>{item.text}</Menu.Item>)
                        }
                    </Menu>

                </Col>
                <Col span={8} style={{ textAlign: 'right' }}>
                    {
                         props.userInfo.username ?
                         <>
                    <Avatar
                        icon={<UserOutlined />}
                        src={baseURL + props.userInfo.avatar}
                        size="small"
                    ></Avatar>
                    <Button type="link" size="small" style={{ color: '#fff' }}>{props.userInfo.username}</Button>
                    <Button type="link" size="small" onClick={props.logout}>退出</Button>
                   </>
                    :
                    <>
                          <Button type="link" onClick={goto.bind(null, '/login?redirectTo='+props.location.pathname)}>登录</Button>
                                <Button type="link" onClick={goto.bind(null, '/reg')}>注册</Button>
                    </>
}
                </Col>

            </Row>



        </Layout.Header>
        {/* <HashRouter>
        <Route path="/home" component={Home} />
        <Route path="/login" component={Login} />
        <Route path="/reg" component={Reg} />
    </HashRouter> */}

        {/*
    <Link to='/home'>首页</Link>
    <Link to='/login'>登入</Link>
    <Link to='/reg'>注册</Link> */}

        {/* 精确匹配 重定向路由
    <Route path="/" component={Home} exact /> */}
        <Layout.Content>
            <Switch>
                <Route path="/home" component={Home} />
                <Route path="/login" component={Login} />
                <Route path="/reg" component={Reg} />
                <Route path='/mine' component={Mine} />
                <Route path="/iq/:id" component={IQ} />
                <Route path="/notfound" render={() =>
                    <div>404</div>} />
                <Route path="/discover" component={Discover} />
                {/* 重定向路由 */}
                <Redirect from="/" to="/home" exact></Redirect>
                {/*
            <Redirect from="*" to="/notfound" /> */}
                <Redirect to="/notfound" />
                {/* 404 */}
            </Switch>
        </Layout.Content>
    </Layout >
}

const mapStateToProps = function (state) {
    return {
        userInfo: state.user.userInfo
    }
}

const mapDispatchToProps=function(dispatch){
     return {
        // login(){
        //     dispatch(login())
        // },
        logout(){
            dispatch({ type: 'logout' })
        }
    }
}
App = connect(mapStateToProps,mapDispatchToProps)(App)

//withRouter 高阶组件
App = withRouter(App) // 获取history: location: createHref: ƒ, push: ƒ, …}
export default App;

// vue-test/uicy/src/App.vue
<template>
  <div id="app">
    <!-- <h3>router-view 显示的内容</h3> -->
    <!-- <nav>  跳转
      <router-link to="/home" tag="span" active-class="active">首页</router-link>
      <router-link to="/reg" active-class="active" replace>注册</router-link>
      <router-link to="/login" active-class="active" event="mouseover">登录</router-link>
    </nav>-->
    <!-- 
    <nav>
      <ul>
        <li v-for="item in nav" :key="item.name" @click="goto(item)" :class="{active:item.path===current}">{{item.text}}</li>
      </ul>
    </nav> -->


    <!-- :default-active="current"   刷新不锁定内容  -->
    <el-row style="background-color:#545c64">
      <el-col :span="12">
        <el-menu mode="horizontal" background-color="#545c64" text-color="#fff" active-text-color="#ffd04b"
          :default-active="current" router>

          <el-menu-item :index='item.path' v-for="item in nav" :key="item.name"><i :class="item.icon"></i>{{item.text}}
          </el-menu-item>


        </el-menu>
      </el-col>
      <el-col :span="12"
        style="border-bottom:solid 1px #e6e6e6;height:61px;overflow:hidden;text-align:right;line-height:61px;padding-right:20px;">
        <el-button type="text" @click="goto('/reg')">注册</el-button>
        <el-button type="text" @click="goto('/login')">登录</el-button>
      </el-col>
    </el-row>
    <!-- 显示  路由信息显示-->
    <router-view></router-view>

  </div>
</template>

<script>
  export default {
    name: 'App',
    data() {
      return {
        nav: [{
          name: "home",
          path: "/home",
          text: "首页",
          icon: "el-icon-s-home"
        }, {
          name: "discover",
          path: "/discover",
          text: "发现",
          icon: "el-icon-view"
        }, {
          name: "cart",
          path: "/cart",
          text: "购物车",
          icon: "el-icon-shopping-cart-2"
        }],
        current: "/home"
      }
    },
    watch: {
      // 监听路由变化，实现高亮效果   newVal新值（path）    oldVal旧值（path）
      "$route.path": function (newVal) {
        //  console.log(newVal,oldVal);
        this.current = newVal;
      }
    },
    methods: {
      goto(path) {
        // this.$router.push(item.path);  跳转 浏览器有记录
        this.$router.replace(path) // 跳转   无浏览器有记录
      }
    },

    //  刷新锁定 声明周期
    created() {
      let {
        path
      } = this.$route;
      this.current = path;
    }

  }
</script>

<style lang="scss">
  body {
    margin: 0;
  }

  .pric {

    span::before,
    del::before {
      content: '￥'
    }

    del {
      color: #999
    }

    span {
      color: red
    }
  }

  @for $i from 1 to 6 {
    .m-#{$i} {
      margin: $i*0.3em;
    }

    .p-#{$i} {
      padding: $i*0.3em;
    }
  }

  nav a {
    margin: 0 10px;
  }

  .active {
    color: #f00;
    font-weight: bold;
  }
</style>
